# Generated by Django 5.1.6 on 2025-05-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(upload_to='app1/static/app1/images/'),
        ),
    ]
