# Generated by Django 5.1.6 on 2025-05-28 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_author_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathProgramFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Общая оценка программы')),
                ('curriculum_opinion', models.TextField(help_text='Соответствие современным требованиям, полнота курсов и т.д.', verbose_name='Ваше мнение о учебном плане')),
                ('teaching_quality', models.TextField(blank=True, help_text='Ваше впечатление от преподавательского состава', verbose_name='Качество преподавания')),
                ('improvements', models.TextField(blank=True, help_text='Ваши предложения по улучшению программы', verbose_name='Что можно улучшить?')),
                ('recommend', models.BooleanField(default=True, verbose_name='Рекомендовали бы вы эту программу?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Отзыв о программе',
                'verbose_name_plural': 'Отзывы о программе',
                'ordering': ['-created_at'],
            },
        ),
    ]
