# Generated by Django 5.1.6 on 2025-05-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_mathprogramfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathprogramfeedback',
            name='rating',
        ),
    ]
