# Generated by Django 5.1.6 on 2025-05-28 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_mathprogramfeedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathprogramfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Оцените программу по шкале от 1 до 10, где 10 - отлично', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка программы (1-10)'),
        ),
    ]
