# Generated by Django 5.1.6 on 2025-05-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_mathprogramfeedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(upload_to='app1/images/'),
        ),
    ]
